### ISSUE TITLE
Add note here about using the basload in ROM

### ISSUE THREAD

**Issue by jakebullet70** [stefan-b-jakobsson/basload#11]
Might want to put a note here about using the basload in ROM. The basload PRG is not included on the SD card anymore.

**Comment by stefan-b-jakobsson** [comment]
Yes, I should probably go on and mark this project as obsolete as well.

**Comment by Thraka** [comment]
Yeah. I came here to see whats new in basload since I as have some incompatibility issues and it turned out I needed to upgrade to the latest emulator release.

I went to the rom repo but it just lists "updates to BASLOAD" in the release notes. But what updates happened? I was hoping to see a changelog or something related to it.

**Comment by stefan-b-jakobsson** [comment]
This project is now marked as obsolete.
